/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;


import mediadorchat.Cliente;

import java.io.IOException;

public class ChatVisual extends javax.swing.JFrame {

    static String name;
    static Cliente cliente;

    public ChatVisual(Cliente cliente) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.cliente = cliente;
        rsscalelabel.RSScaleLabel.setScaleLabel(jlabelicon, "src/img/twitchbanner.png");
    }

    public void setName(String name) {
        this.name = name;
    }


    public void creaConexion() {
        //this.setVisible(true);
        //Cliente cliente = new Cliente("gil", "localhost", 1414);
        cliente.init();
        //RecibirDatos();
    }

    public void escribeMsg(String msg) {
        jTextArea2.append(msg);
    }

    private void setBtnEnviarBroadCast(java.awt.event.ActionEvent evt) {
        String msg = mensajeTxt1.getText();
        String comando = "enviar -m '" + msg +"' -t 'BroadCast";
        cliente.EnviarDatos(comando);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jlabelicon = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        enviarA = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        mensajeTxt2 = new javax.swing.JTextField();
        mensajeTxt1 = new javax.swing.JTextField();
        btnEnviarBroadCast = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(180, 164, 212));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setBackground(new java.awt.Color(216, 207, 232));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 5));
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 580, 280));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuarios Conectados");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 200, 30));

        jlabelicon.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jlabelicon.setForeground(new java.awt.Color(255, 255, 255));
        jlabelicon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 207, 232), 5));
        jPanel1.add(jlabelicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 580, 170));

        jTextArea3.setBackground(new java.awt.Color(216, 207, 232));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea3.setRows(5);
        jTextArea3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 5));
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 270, 410));

        enviarA.setBackground(new java.awt.Color(204, 204, 255));
        enviarA.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        enviarA.setForeground(new java.awt.Color(123, 92, 180));
        enviarA.setText("Enviar a...");
        jPanel1.add(enviarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 150, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(204, 204, 255));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(123, 92, 180));
        btnCerrarSesion.setText("Cerrar Sesion");
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, -1, -1));

        mensajeTxt2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jPanel1.add(mensajeTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 220, 30));

        mensajeTxt1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jPanel1.add(mensajeTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 420, 30));

        btnEnviarBroadCast.setBackground(new java.awt.Color(204, 204, 255));
        btnEnviarBroadCast.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        btnEnviarBroadCast.setForeground(new java.awt.Color(123, 92, 180));
        btnEnviarBroadCast.setText("Enviar Todos");
        jPanel1.add(btnEnviarBroadCast, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 190, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return
     */




    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatVisual(cliente).setVisible(true);

            }
        });



    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarA;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEnviarBroadCast;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel jlabelicon;
    private javax.swing.JTextField mensajeTxt1;
    private javax.swing.JTextField mensajeTxt2;
    // End of variables declaration//GEN-END:variables
}
