/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import mediadorchat.Cliente;
import mediadorchat.Conexion;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.util.ArrayList;

public class LoginVisul extends javax.swing.JFrame {


    SingletonUsuario usuarios = new SingletonUsuario();
    String nombre;
    boolean login = false;
    static Cliente cliente;

    public LoginVisul() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel1, "src/img/twitch9.png");
        this.cliente = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usuarioTxt = new javax.swing.JTextField();
        resgistrarBtn = new javax.swing.JButton();
        inciarSesionbtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(100, 68, 164));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(180, 164, 212));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 207, 232), 5));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 280));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bienvenido!");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, 30));

        usuarioTxt.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jPanel1.add(usuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 320, 30));

        resgistrarBtn.setBackground(new java.awt.Color(204, 204, 255));
        resgistrarBtn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        resgistrarBtn.setForeground(new java.awt.Color(123, 92, 180));
        resgistrarBtn.setText("Registrar");
        resgistrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resgistrarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resgistrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 150, -1));

        inciarSesionbtn1.setBackground(new java.awt.Color(204, 204, 255));
        inciarSesionbtn1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        inciarSesionbtn1.setForeground(new java.awt.Color(123, 92, 180));
        inciarSesionbtn1.setText("Iniciar Sesion");
        inciarSesionbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inciarSesionbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(inciarSesionbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String returnName(){
        return this.nombre;
    }

    public boolean returnLogin(){
        return this.login;
    }

    private void resgistrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resgistrarBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        RegistrarVisual registrarVisual = new RegistrarVisual(usuarios);
        registrarVisual.setVisible(true);
    }//GEN-LAST:event_resgistrarBtnActionPerformed

    private void inciarSesionbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inciarSesionbtn1ActionPerformed
        // TODO add your handling code here:

        String name = usuarioTxt.getText();

        if (usuarios.exist(name)){
            Cliente cliente = new Cliente(name, "localhost", 1414);

            JOptionPane.showMessageDialog(this, "Bienvenido!!!", "", 1);

            this.dispose();

            ChatVisual chat = new ChatVisual(cliente);
            chat.setVisible(true);
            chat.creaConexion();


        } else {
            JOptionPane.showMessageDialog(this, "El usuario no existe", "Error", 0);
        }

        
    }//GEN-LAST:event_inciarSesionbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginVisul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginVisul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginVisul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginVisul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginVisul().setVisible(true);
            }
        });


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inciarSesionbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton resgistrarBtn;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
